config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
  resources :pages
  root 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/page.rb
class Page < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def new

  end

  def create
    @page = Page.new(page_params)

    @page.save
    redirect_to @page
  end

  def show
    @page = Page.find(params[:id])
  end

  def index
    @pages = Page.all
  end

  private
    def page_params
      params.require(:page).permit(:title, :text)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HelloWorld</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/index.html.erb
<h1>Listing Pages</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Text</th>
  </tr>

  <% @pages.each do |page| %>
    <tr>
      <td><%= page.title %></td>
      <td><%= page.text %></td>
      <td><%= link_to 'Show', page_path(page) %></td>
    </tr>
    <% end %>
</table>

app/views/pages/new.html.erb
<h1> hello new you </h1>
<%= form_with scope: :page, url: pages_path, local: true do |form| %>
  <p>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
  </p>

  <p>
    <%= form.label :text %>
    <%= form.text_area :text %>
  </p>

  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/pages/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @page.title %>
</p>

<p>
  <strong>Text:</strong>
  <%= @page.text %>
</p>

app/views/welcome/index.html.erb
<h1>Hello <b>Rails 5</b> World!</h1>